# Generated by Django 5.0.4 on 2024-04-13 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_post_thumbails'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(auto_created=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
